### PR TITLE
Fix TypeError while using require after clean installation

### PR DESCRIPTION
**Pull request by a1exsh**
Don't try to look into last_update object unless we actually have one.

### CODE REVIEW

**Comment by gargravarr** [comment]
:+1:

**Comment by tuxlife** [comment]
:-1:

**Comment by tuxlife** [comment]
@a1exsh can you please describe your Error. It change doesn't make sense. It is nearly the same with more lines.

**Comment by a1exsh** [comment]
The actual error is like this:
```
Traceback (most recent call last):
  File "/home/oshulgin/.local/bin/zaws", line 11, in <module>
    sys.exit(main())
  File "/home/oshulgin/.local/lib/python3.5/site-packages/zalando_aws_cli/cli.py", line 331, in main
    cli()
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/oshulgin/.local/lib/python3.5/site-packages/zalando_aws_cli/cli.py", line 144, in require
    (account_name and (account_name, role_name) != (last_update['account_name'], last_update['role_name']))):
TypeError: 'NoneType' object is not subscriptable
```
To reproduce it, remove your existing `~/.config/zalando-aws-cli/zalando-aws-cli.yaml` file and try `zaws require my_account`.

**Comment by tuxlife** [comment]
fixed with #18

**Pull request closed without merging**
