### PR TITLE
make require the default command instead of login

### PR DESCRIPTION
**Pull request by musiKk**
Not sure if anything speaks against it. I think it's safe to assume that a valid existing AWS token can be used in the common case.

### CODE REVIEW

**Comment by hjacobs** [comment]
@musiKk I think the only problem is that the credentials might be valid for a short time frame only (right now users can safely assume that `zaws` gives them credentials valid for one hour).

**Comment by musiKk** [comment]
This is a valid concern.

Feel free to close at your discretion.

**Comment by hjacobs** [comment]
@musiKk I'm unsure and will give it a second thought :smirk:

**Comment by ideahitme** [comment]
this is too old and closing this due to migration to internal github

**Pull request closed without merging**
